name: expense_tracker
description: "Application is a way to provide visibility to budget and expenses for where multiple users can interact with a shared ledger"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  uuid: ^4.5.1
  intl: ^0.19.0
  dotted_border: ^2.1.0
  foundation: ^0.0.5
  multi_dropdown: ^3.0.1
  font_awesome_flutter: ^10.8.0
  flutter_dotenv: ^5.2.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  rxdart: ^0.27.7
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.5
  flutter_colorpicker: ^1.1.0
  cloud_functions: ^4.7.6
  package_info_plus: ^8.1.3
  fl_chart: ^0.68.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
